Start of a FindOpenFOAM CMake module
lebuller/enrico pull request #1
Opened 2020-06-12 20:51 UTC by pshriwise

2020-06-14 18:14 UTC, pshriwise commented
Made some small updates here that allow us to set properties of the `chtMultiRegionFoam` target instead of the global calls (`link_directories` and direct setting of the CMake CXX flags). By adding calls to find the full paths of the library via `find_library` we no longer need to set the link directories and can avoid this.

2020-06-15 14:20 UTC, lebuller requested changes

2020-06-15 14:20 UTC, lebuller commented on cmake/FindOpenFOAM.cmake
> +  message(STATUS "OpenFOAM ${OPENFOAM_LINK_DIRS}")
We can probably remove this message statement on `OPENFOAM_LINK_DIRS` at this point

2020-06-15 14:20 UTC, lebuller commented on cmake/FindOpenFOAM.cmake
> +  $ENV{WM_PROJECT_DIR}/src/meshTools/lnInclude/
Changing the `$ENV{WM_PROJECT_DIR}/src` to use `$ENV{FOAM_SRC}` instead may be a good plan. This goes for all of the libraries listed

2020-06-15 14:20 UTC, lebuller commented on cmake/FindOpenFOAM.cmake
> +  # target_link_directories(chtMultiRegionFoam ${OPENFOAM_LINK_DIRS})
Should we go ahead and make the same changes to the `openfoam-imported` target that were made to the `chtMultiRegionFoam` target in terms of how we are getting around the lack of `target_link_directories` in the current version of `cmake` on `ulam`

2020-06-15 15:30 UTC, pshriwise commented
Just addressed a couple of these comments. With respect to the `openfoam-imported` target, as this is a working branch I think I'll leave it as is for now if that's ok with you. Once we're ready to actually use the target I'm thinking we can revisit it.

2020-06-15 17:21 UTC, merged